spring:
  application:
    name: schedule
  output:
    ansi:
      enabled: always

# Configuration des logs - affichage simplifié
logging:
  pattern:
    console: "%msg%n"

# Configuration du solveur CP-SAT OR-Tools
solver:
  log-search-progress: true
  max-time-in-seconds: 300
  num-workers: 4
  search-branching: "AUTOMATIC"
  preferred-variable-order: "IN_ORDER"
  cp-model-presolve: true
  cp-model-probing-level: 2